### ISSUE TITLE
EPIC: add support for variants

### ISSUE THREAD

**Issue by ThomasLohner** [ongr-io/Demo#157]
we should provide a documented way for using variants. otherwise every project will implement it's own magic. since nearly every shop needs this features, it makes sense to keep this consistent

**Comment by saimaz** [comment]
Implemented in https://github.com/ongr-io/ApiBundle/pull/113

**Comment by saimaz** [comment]
Oh, Docs for this specific topic are missing, but I created an issue for it with 1.0 milestone https://github.com/ongr-io/ApiBundle/issues/114
