### ISSUE TITLE
Add "stable" Branch

### ISSUE THREAD

**Issue by jkrug** [ongr-io/Demo#158]
Please add a stable branch or something simular whre one could checkaout a running version.

I know that ONGR is wip at the moment but if you checkout the master branch, nothing will work, which is a step backwards.
See https://github.com/jkrug/ongr-sandbox/tree/stable for example

**Comment by saimaz** [comment]
We won't add any new branch. To fix this issue I will add more clear instruction in the readme with point to the releases page from where to download a stable working version of Demo app.

**Comment by jkrug** [comment]
I don't care how to check it out. You could also add a tag or name the latest stable commit in a readme or do something similar. My point is, that we had a version that could be installed by checking out that repo. Now we're working on it and if you follow the same instructions, it doesn't work anymore.

**Comment by saimaz** [comment]
Closed with https://github.com/ongr-io/Demo/commit/d218d7dd20c2c67e8ddb778c7ddc344aa14b8fd4
