### ISSUE TITLE
Update Quickstart Installation Guide Readme

### ISSUE THREAD

**Issue by twslade** [ongr-io/Demo#161]
Vagrant submodule was removed https://github.com/ongr-io/Demo/commit/1b74c5f3af48c326109770cdf93b9232ed166b30 but installation guide readme references vagrant path for installation in step 5. https://github.com/ongr-io/Demo/blob/master/src/ONGR/DemoBundle/Resources/doc/index.rst#step-5-start-the-virtual-machine-using-vagrant

**Comment by nifr** [comment]
Yeah, what happened to the submodule?

**Comment by kazgurs** [comment]
It's no longer needed. Checkout our updated [testing VM](https://github.com/ongr-io/testing-vm). Clone it, check out the Demo code or any other ONGR bundle into a `public` subdirectory and `vagrant up`. Please, leave an issue if anything does not work as expected. We're working on revamping all docs completely. Demo docs will be also be updated soon.

**Comment by saimaz** [comment]
We thought that submodule will be easy way to use a box. Turns out it's not that easy for most of the  poeple. I currently working on the new docs and there will be fresh install setup for the `Demo`.
