### ISSUE TITLE
Windows OS - permission denied to modify etc/hosts file

### ISSUE THREAD

**Issue by FDiskas** [ongr-io/Demo#99]
There is an error then booting up a vagrant. The plugin "vagrant-hostsupdater" is trying to modify  ets/hosts file which is denied by the permissions of the current user.
I suggest you to use a better alternative plugin: "vagrant-hostmanager" and first of all - check if user has that plugin and if not - install it.

**Comment by FDiskas** [comment]
vagrant-hostmanager plugin
------
More info could be found here: https://github.com/smdahlen/vagrant-hostmanager
Windows support

Hostmanager will detect Windows guests and hosts and use the appropriate path for the hosts file: ```%WINDIR%\System32\drivers\etc\hosts```

By default on a Windows host, the hosts file is not writable without elevated privileges. If hostmanager detects that it cannot overwrite the file, it will attempt to do so with elevated privileges, causing the UAC prompt to appear.

**Comment by saimaz** [comment]
I assume you tried to run everything on the windows. How was with the shared files and performance? Can you tell me on which operating system (win 7, 8, 8.1) you have checked?

**Comment by FDiskas** [comment]
Yes I tried this on Windows 8.1
The shared files is working good, but rendering time is to bad.
Used memory and render time is to big.

![screencapture-ongr-dev-_profiler-8ccb6a](https://cloud.githubusercontent.com/assets/468006/6305824/9987e26c-b936-11e4-8908-ccf97a13c753.png)
![screencapture-ongr-dev-_profiler-22f206](https://cloud.githubusercontent.com/assets/468006/6305825/998a9c0a-b936-11e4-95dd-ffcc32d4ab16.png)

**Comment by tautrimas** [comment]
Hey, @FDiskas. Default `vboxfs` is slow for thousands of Composer vendor files. Can you try https://github.com/GM-Alex/vagrant-winnfsd? NFS is one of the most convenient ways to share files with VirtualBox.

**Comment by FDiskas** [comment]
Much better now. Thanks for suggested plugin.

![screencapture-ongr-dev-_profiler-2847c3](https://cloud.githubusercontent.com/assets/468006/6310955/cd4d5cc0-b964-11e4-974f-77debbe3441f.png)
![screencapture-ongr-dev-_profiler-605368](https://cloud.githubusercontent.com/assets/468006/6310974/0e06dc78-b965-11e4-9148-b414940a6f86.png)

**Comment by saimaz** [comment]
See the repo here: https://github.com/ongr-io/testing-vm It should support windows now. If you still have any problem with any OS. Create an issue there.
